version: "1.0"

volumes:
  building_query_data:
  building_query_gradle_data:

networks:
  api_gateway_net:
    external: true
  query_database_net:
    external: true
  rabbitmq_net:
    external: true

services:
  building_query_service:
    container_name: "building-query-service"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${BUILDING_QUERY_HOST_PORT}:${BUILDING_QUERY_CONTAINER_PORT}
    volumes:
      - building_query_data:${BUILDING_QUERY_SERVICE_VOLUMES}
      - building_query_gradle_data:${BUILDING_QUERY_GRADLE_VOLUMES}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_gateway_net
      - query_database_net
      - rabbitmq_net
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      APPLICATION_NAME: ${APPLICATION_NAME}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VIRTUAL_HOST: ${RABBITMQ_VIRTUAL_HOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_IGNORE_DECLARATION_EXCEPTION: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION}
      RABBITMQ_CONCURRENT_CONSUMERS: ${RABBITMQ_CONCURRENT_CONSUMERS}
      RABBITMQ_MAX_CONCURRENT_CONSUMERS: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS}
      RABBITMQ_RECEIVE_TIMEOUT: ${RABBITMQ_RECEIVE_TIMEOUT}
